# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/lenovo/b8080f/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/lenovo/b8080f

PRODUCT_COPY_FILES += \
    vendor/lenovo/b8080f/proprietary/etc/E08QL_s5k4h5yb_module_info.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/E08QL_s5k4h5yb_module_info.xml \
    vendor/lenovo/b8080f/proprietary/vendor/lib/E08QL_libTsAe.so:$(TARGET_COPY_OUT_VENDOR)/lib/E08QL_libTsAe.so \
    vendor/lenovo/b8080f/proprietary/vendor/lib/E08QL_libTsAf.so:$(TARGET_COPY_OUT_VENDOR)/lib/E08QL_libTsAf.so \
    vendor/lenovo/b8080f/proprietary/vendor/lib/E08QL_libTs_J_Accm.so:$(TARGET_COPY_OUT_VENDOR)/lib/E08QL_libTs_J_Accm.so \
    vendor/lenovo/b8080f/proprietary/vendor/lib/E08QL_libTs_J_Awb.so:$(TARGET_COPY_OUT_VENDOR)/lib/E08QL_libTs_J_Awb.so \
    vendor/lenovo/b8080f/proprietary/vendor/lib/libTs_J_Awb.so:$(TARGET_COPY_OUT_VENDOR)/lib/libTs_J_Awb.so \
    vendor/lenovo/b8080f/proprietary/vendor/lib/libmmcamera2_stats_algorithm.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_stats_algorithm.so \
    vendor/lenovo/b8080f/proprietary/vendor/lib/libmmcamera_fidelix_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_fidelix_eeprom.so \
    vendor/lenovo/b8080f/proprietary/vendor/lib/libsec-ril.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsec-ril.so \
    vendor/lenovo/b8080f/proprietary/vendor/lib/E08QL_libchromatix_s5k4h5yb_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/E08QL_libchromatix_s5k4h5yb_common.so \
    vendor/lenovo/b8080f/proprietary/vendor/lib/E08QL_libchromatix_s5k4h5yb_common_res0.so:$(TARGET_COPY_OUT_VENDOR)/lib/E08QL_libchromatix_s5k4h5yb_common_res0.so \
    vendor/lenovo/b8080f/proprietary/vendor/lib/E08QL_libchromatix_s5k4h5yb_common_res1.so:$(TARGET_COPY_OUT_VENDOR)/lib/E08QL_libchromatix_s5k4h5yb_common_res1.so \
    vendor/lenovo/b8080f/proprietary/vendor/lib/E08QL_libchromatix_s5k4h5yb_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/E08QL_libchromatix_s5k4h5yb_default_video.so \
    vendor/lenovo/b8080f/proprietary/vendor/lib/E08QL_libchromatix_s5k4h5yb_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/E08QL_libchromatix_s5k4h5yb_liveshot.so \
    vendor/lenovo/b8080f/proprietary/vendor/lib/E08QL_libchromatix_s5k4h5yb_panorama.so:$(TARGET_COPY_OUT_VENDOR)/lib/E08QL_libchromatix_s5k4h5yb_panorama.so \
    vendor/lenovo/b8080f/proprietary/vendor/lib/E08QL_libchromatix_s5k4h5yb_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/E08QL_libchromatix_s5k4h5yb_preview.so \
    vendor/lenovo/b8080f/proprietary/vendor/lib/E08QL_libchromatix_s5k4h5yb_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/E08QL_libchromatix_s5k4h5yb_snapshot.so \
    vendor/lenovo/b8080f/proprietary/vendor/lib/E08QL_libchromatix_s5k4h5yb_video_hd.so:$(TARGET_COPY_OUT_VENDOR)/lib/E08QL_libchromatix_s5k4h5yb_video_hd.so \
    vendor/lenovo/b8080f/proprietary/vendor/lib/E08QL_libchromatix_s5k4h5yb_zsl.so:$(TARGET_COPY_OUT_VENDOR)/lib/E08QL_libchromatix_s5k4h5yb_zsl.so \
    vendor/lenovo/b8080f/proprietary/vendor/lib/E08QL_libchromatix_s5k4h5yb_zslshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/E08QL_libchromatix_s5k4h5yb_zslshot.so \
    vendor/lenovo/b8080f/proprietary/vendor/lib/libmmcamera2_iface_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_iface_modules.so \
    vendor/lenovo/b8080f/proprietary/vendor/lib/libmmcamera2_imglib_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_imglib_modules.so \
    vendor/lenovo/b8080f/proprietary/vendor/lib/libmmcamera2_isp_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_isp_modules.so \
    vendor/lenovo/b8080f/proprietary/vendor/lib/libmmcamera2_sensor_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_sensor_modules.so \
    vendor/lenovo/b8080f/proprietary/vendor/lib/libmmcamera2_stats_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_stats_modules.so \
    vendor/lenovo/b8080f/proprietary/vendor/lib/libmmcamera_s5k4h5yb.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_s5k4h5yb.so \
    vendor/lenovo/b8080f/proprietary/vendor/lib/liboemcamera.so:$(TARGET_COPY_OUT_VENDOR)/lib/liboemcamera.so
